### ISSUE TITLE
一些小观点

### ISSUE THREAD

**Issue by MrShiF** [heikanet/whohk#2]
话说大佬，这是linux的应急，用py写的话会不会比较不方便，有些机子不能安装py。考不考虑用shell脚本语言写一个咧

**Comment by ssrsec** [comment]
> 话说大佬，这是linux的应急，用py写的话会不会比较不方便，有些机子不能安装py。考不考虑用shell脚本语言写一个咧

我之前都是打包成二进制的，不需要相关依赖。
